const actions = {
  //BEHAVIOUR ACTION SAGAS
  ADD_LOCATION: 'ADD_LOCATION',
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  //COMMON ACTION SAGAS
  ADD_LOCATION_REQUEST: 'ADD_LOCATION_REQUEST',
  CHANGE_LOCATION_REQUEST: 'CHANGE_LOCATION_REQUEST',
  GET_VIDEOS_REQUEST: 'GET_VIDEOS_REQUEST',
};

export default actions;
